server:
  port: 9191

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
